### ISSUE TITLE
Reference to another card has light background (and font)

### ISSUE THREAD

**Issue by edison23** [Xaymar/Trello-Digital-Dark#1]
When refering to another card, the link retains light bg color even with black style on. See pic.

![trello-dark-bug](https://cloud.githubusercontent.com/assets/1723800/18275501/8f27e7d6-7447-11e6-8eb4-e9ac6b31647b.png)

**Comment by Xaymar** [comment]
Should be fixed now.

**Comment by edison23** [comment]
I reinstalled the style from official repo few minutes ago and the bug is still repro for me.

![screenshot-trello com 2016-09-07 08-23-27](https://cloud.githubusercontent.com/assets/1723800/18301804/6c77c368-74d4-11e6-8385-2e3f81c79a3e.png)

**Comment by Xaymar** [comment]
Do you have a trello board I can test this on?

**Comment by edison23** [comment]
Not right now, but I think I know where the problem is. For comments, it's fixed, but it's still repro in description. Is that a case for you too?

**Comment by Xaymar** [comment]
Should be fixed now.

**Comment by edison23** [comment]
yes, fixed now! thank you :)
